### ISSUE TITLE
nvdia GTX970 card use vulkan mode issue

### ISSUE THREAD

**Issue by newengineer123** [pineappleEA/pineapple-src#102]
i have a computer ,use GTX970 ,when  use 472.12-desktop-win10-win11-64bit-international-dch-whql driver the pic is right (NVIDIA NVIDIA GeForce GTX 970 (Vulkan v1.2.175, Driver v472.12.0.0))  but i update the driver to 527.86_geforce_win11_win10_64bit_dch_international and 528.02-desktop-win10-win11-64bit-international-dch-whql the pic is non and the app is crash,so do the last gtx driver ,idont know why  thanks。
我有一台GTX970的电脑，使用472.12-desktop-win10-win11-64bit-international-dch-whql driver the pic is right (NVIDIA NVIDIA GeForce GTX 970 (Vulkan v1.2.175, Driver v472.12.0.0))驱动版本，使用是正常的，当我更新我的显卡驱动版本到527.86_geforce_win11_win10_64bit_dch_international and 528.02-desktop-win10-win11-64bit-international-dch-whql时，模拟器直接不显示，并闪退，这一版驱动有最新的VULKAN（GeForce GTX 970 (Vulkan v1.3.236, Driver v527.86.0.0)），更新至最新的驱动版本也是一样，不能显示。我想知道是不是编译的时候使用的VULKAN版本就是Vulkan v1.2.175，谢谢

**Comment by MGThePro** [comment]
This is an issue with yuzu, not pineapple. We just distribute the builds, any issues with the emulator should be reported to the emulator developers instead.
