### ISSUE TITLE
Fire Emblem Engage dialogue still crash on the lastest version on appimage but not in the .exe EA

### ISSUE THREAD

**Issue by Henatsuka** [pineappleEA/pineapple-src#103]
On 3310 to 3316 it's still crashing on my Steam Deck when a dialogue box opens, but when I try on my Windows PC with the EA .exe it doesn't crash at all, I don't know if the problem is on the yuzu side or the appimage side

**Comment by MGThePro** [comment]
It's on the yuzu side because the appimages on pineapple are provided by yuzu
