### ISSUE TITLE
api-ms-win-core-com-l1-1-0.dll, api-ms-win-downlevel-kernel32-l2-1-0.dll, and 0xc000007b errors since mainline yuzu version 1168

### ISSUE THREAD

**Issue by fm3845w0** [pineappleEA/pineapple-src#104]
### Affected Build(s)

Mainline >= 1168

### Description of Issue

When I launch yuzu.exe, it errors:

"The program can't start because api-ms-win-core-com-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

After I relaunch with that DLL, it errors differently:

"The program can't start because api-ms-win-downlevel-kernel32-l2-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

After I relaunch with that DLL, it errors differently:

"The application was unable to start correctly (0xc000007b). Click OK to close the application."

I cannot progress past this error message.

### Regression Tracking

The problem is absent in mainline-0-1167. It is introduced in 0-1168:

https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1168

### Workarounds

When I launch mainline-0-1167, I can boot games.

When I launch yuzu-cmd.exe, instead of yuzu.exe, I can boot games.

When I launch Ryujinx, I can boot games.

### Expected Behavior

yuzu.exe should show the UI and boot games.

### Reproduction Steps

Run the yuzu.exe from mainline-0-1168 or later.

### System Configuration

The problem occurs on Windows 7.

The problem occurs on both the GTX 980 and 1070 graphics cards.

The problem occurs on both a 6th generation Intel i7 and on AMD Ryzen 5.

The problem coexists with an installation of either the .NET Framework 4.7.2 or 4.8.

The problem occurs regardless of VC redistributables (2008, 2010, 2012, 2013, 2015-2022).

The problem occurs despite drivers and updates being up to date.

### Recourse

I reported this issue on github.com/yuzu-emu/yuzu/issues and the issue was shut down by liamwhite with the comment "Windows 7 is not supported." Since those with a toolchain to build yuzu cannot fix the issue due to project policy, I come to pineappleEA for recourse.

### Request

Investigate the changes here to isolate and fix what causes the problem:

https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1168

Build pineappleEA with these fixes in the future.

### Assistance

I am available to test builds on request.

### Benefits

With this fixed, pineappleEA will develop a reputation as the alternative to yuzu for people on Windows 7. This is free advertising and good PR for the pineappleEA project.

**Comment by enkiros** [comment]
Just a personal opinion here. The population of desktop users of win 7 with decent hardware capable of switch emulation must be infinitesimal compared to win 10 and 11 users. I see pineapple as the EA builds guy, I don't think they need the additional good PR. It might be a good project for someone interested or with experience in backporting software to older windows versions tho

**Comment by MGThePro** [comment]
Not viable. At best it's some build settings, which would still require to set up and maintain a build system via github actions.

We did something similar to this for linux until recently, but we stopped because it was way too much effort to keep it running and working.

At worst it would require changes to the source code which would basically turn pinEApple into a full on fork which is even more work to maintain.

Honestly, just stop using Windows 7. With its lack of updates it's no longer safe to use and if you refuse to use Windows 11 there's always linux.

**Comment by pbanj** [comment]
> Not viable. At best it's some build settings, which would still require to set up and maintain a build system via github actions.
> 
> We did something similar to this for linux until recently, but we stopped because it was way too much effort to keep it running and working.
> 
> At worst it would require changes to the source code which would basically turn pinEApple into a full on fork which is even more work to maintain.
> 
> Honestly, just stop using Windows 7. With its lack of updates it's no longer safe to use and if you refuse to use Windows 11 there's always linux.

hell they could even go to 10. most of the crap people hate about 10+ was added to 7 and 8/8.1 with updates. so not only is all the tracking there, but the security is horrible because it's no longer updated.

**Comment by imagochan** [comment]
you could try installing Windows LTSC on your computer, it's lightweight compared to stock Win 10.
