### ISSUE TITLE
3561 controller broken

### ISSUE THREAD

**Issue by TheOriginalBabu** [pineappleEA/pineapple-src#109]
Belarus stronk

**Comment by martixjohn** [comment]
same problem

**Comment by cordlessdev** [comment]
Can confirm, controller axes broken

**Comment by billzhuang** [comment]
same problem

**Comment by 74oshua** [comment]
I'm assuming this is about the joysticks not being centered anymore:
![controller](https://user-images.githubusercontent.com/20734879/236661179-dd4cde84-cb19-4cef-b3be-57e00e73da41.png)

Tried both with and without BetterJoy

**Comment by 74oshua** [comment]
Wild guess, but I think 

https://github.com/pineappleEA/pineapple-src/blob/4fa09f2af956fa08fe3c2c638bf92618998eedc6/src/input_common/input_engine.cpp#L62

should be a +=

**Comment by SirenBrink** [comment]
Same issue here. Really thought my controller was drifting, but it's just the app.

**Comment by MGThePro** [comment]
This is an issue on yuzu's end, we just reupload builds.
