### ISSUE TITLE
Two licences

### ISSUE THREAD

**Issue by gekkowrld** [pineappleEA/pineapple-src#111]
There are to licenses in the code [license](https://github.com/pineappleEA/pineapple-src/blob/main/license.txt) and this one [LICENSE](https://github.com/pineappleEA/pineapple-src/blob/main/LICENSE.txt). Both are GNU GPL. Maybe one can be removed to avoid redundacy

**Comment by Ashu104** [comment]
Additionally, some licenses may not be compatible with each other, which means that using code under two incompatible licenses may not be legally allowed. For example, if one license requires that the code be distributed under an open-source license, but the other license requires that the code be kept proprietary, it may not be possible to comply with both licenses simultaneously.

**Comment by MGThePro** [comment]
Ah, probably that issue with the script that fails to remove/rename files. I'll have to fix that eventually. For the time being, I'll just remove the license.txt, the "real" one is the one with all uppercase

> Additionally, some licenses may not be compatible with each other

I doubt that's an issue, they're both the same licenses
