### ISSUE TITLE
The gyro will stop working after playing with the pro controller for a while, and moving the right joystick will also not be effective. After restarting, it will work for a while again, and then stop working. Version: 3571.

### ISSUE THREAD

**Issue by 2435043xia** [pineappleEA/pineapple-src#112]
The gyro will stop working after playing with the pro controller for a while, and moving the right joystick will also not be effective. After restarting, it will work for a while again, and then stop working. Version: 3571.

**Comment by MGThePro** [comment]
We dont develop yuzu, we just distribute the builds. Report this to the yuzu developers.
