### ISSUE TITLE
Exception exit when program reads archive

### ISSUE THREAD

**Issue by yanyuqi615** [pineappleEA/pineapple-src#115]
[yuzu_log.txt](https://github.com/pineappleEA/pineapple-src/files/11458245/yuzu_log.txt)
![屏幕截图 2023-05-12 102310](https://github.com/pineappleEA/pineapple-src/assets/60741566/e2ef0331-7296-4241-b640-7067aabdd607)
![屏幕截图 2023-05-12 102457](https://github.com/pineappleEA/pineapple-src/assets/60741566/be1ebfd4-e132-4cc4-adcb-381df5729dcf)
![屏幕截图 2023-05-12 102504](https://github.com/pineappleEA/pineapple-src/assets/60741566/146545f3-c5e7-4237-9cb3-8c661852830c)
![屏幕截图 2023-05-12 102511](https://github.com/pineappleEA/pineapple-src/assets/60741566/0a4ecf61-a1ab-4e26-9bc9-9d8729552c4b)

https://github.com/pineappleEA/pineapple-src/assets/60741566/c3dfcc3c-a6d2-4053-9aa6-e0e834f7cac8

![屏幕截图 2023-05-12 100550](https://github.com/pineappleEA/pineapple-src/assets/60741566/95fe7b96-1629-4c25-ada8-3185dd6f5ba4)
![屏幕截图 2023-05-12 102636](https://github.com/pineappleEA/pineapple-src/assets/60741566/595461ca-8fdf-4437-b38a-7db8a57c089e)

CPU 6800H GPU:680M

**Comment by yanyuqi615** [comment]
![image](https://github.com/pineappleEA/pineapple-src/assets/60741566/e64fbaa3-f986-408c-a32f-20e5ed89b057)

**Comment by zhongfly** [comment]
report bug to yuzu repo

**Comment by MGThePro** [comment]
We dont develop yuzu, we just distribute the builds. Report this to the yuzu developers.
