### ISSUE TITLE
Vulkan - Crash in the depths with 4gb vram gpu ( Zelda Totk)

### ISSUE THREAD

**Issue by antoi8** [pineappleEA/pineapple-src#117]
many users have this problem. Especially owners of AMD Rx cards with 4 gb of vram. The game crashes or doesn't even load saves at all if you are in the depths with Vulkan api.  Please fix it.

**Comment by MGThePro** [comment]
We dont develop yuzu, we just distribute the builds. Report these kinds of things to the yuzu developers directly.

Although I think this was supposed to be fixed a couple of updates ago.

**Comment by MGThePro** [comment]
Read the message above.

Just use the recompression feature they added a few versions ago.
