### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by baconsplit** [pineappleEA/pineapple-src#122]
Hey I am trying to build from source myself, but I get following errors in Visual Studio 2022
![image](https://github.com/pineappleEA/pineapple-src/assets/63647668/e053cb0d-961b-41d2-a377-298f789eae8e)

The CMake configuration seemed to be successful 
![image](https://github.com/pineappleEA/pineapple-src/assets/63647668/e2813213-a00e-4737-a4d0-177a21042020)

And I selected the yuzu project as start project and try to build the Release.

I can provide additional information if needed, but in general:
Windows 10 22H2 Build 19045.3031
Vulkan SDK is installed
Visual Studio C++ support is installed

**Comment by MGThePro** [comment]
Did you use the source code in the repo or from the archive in the windows release

**Comment by baconsplit** [comment]
Archive in the windows release, and then also did 
git submodule update --init --recursive
for any external dependencies

**Comment by baconsplit** [comment]
I get the same errors when I try to build the development repo of yuzu. Might open an issue there, or check if anyone had the same issue there. Will post here again accordingly

**Comment by baconsplit** [comment]
Apparently just building the project/solution again, without select re-build seems to resolve the issue.
