### ISSUE TITLE
Will compile Android build and release it ?

### ISSUE THREAD

**Issue by Soulize** [pineappleEA/pineapple-src#123]
As what title said

**Comment by Soulize** [comment]
seems its codes have been included in https://github.com/pineappleEA/pineapple-src/tree/main/src
/android/

**Comment by MGThePro** [comment]
No, the builds aren't available to us in the way we download Windows and Linux builds.

Most likely the only way to obtain builds is to download them from the play store directly. Compiling isn't something I'd want to do because it has too many downsides.
