### ISSUE TITLE
3604 Breaks Windows 1809 Compatibility

### ISSUE THREAD

**Issue by HiroTDK** [pineappleEA/pineapple-src#126]
Something changed in 3604 that causes Yuzu EA to crash on Windows 1809. The yuzu log is cut-off mid string with no indication of issue, but the Windows crash dump gives this:

> (b8c.edc): Security check failure or stack buffer overrun - code c0000409 (first/second chance not available)
ucrtbase!abort+0x4e:
00007ffb`6b02e77e cd29            int     29h

Yuzu EA crashes, however Yuzu runs perfectly fine. After encountering someone else with the same issue and OS version, I went back through the source for both EA and Mainline and it looks like the time changes in 3604 haven't been pushed to the mainline Yuzu builds.

**Comment by MGThePro** [comment]
We don't develop yuzu, we just distribute the builds. These kinds of issues need to be reported to the yuzu developers. But make sure it is reproducible on mainline first, they don't like when non-patrons report issues on early access builds.
