### ISSUE TITLE
Q: Why has this feature been discontinued since v3627?

### ISSUE THREAD

**Issue by MegaMimh** [pineappleEA/pineapple-src#127]
Hi,
Do you know why the feature that allowed you to go to the mods or saves folder Etc... when a game is launched in Yuzu, has been removed since version 3627? It was a handy feature.

Thank you for all your work, which I really appreciate.

Before: (Right-click when a game is launched and the menu appears )
![screenshot 2023-06-03 162518](https://github.com/pineappleEA/pineapple-src/assets/66998954/874d11b1-8675-43a1-b25c-46208ffd1160)

Now: (Right-click when a game is launched and nothing happens)
![screenshot 2023-06-03 164519](https://github.com/pineappleEA/pineapple-src/assets/66998954/bd972b9d-6af8-467f-a3d8-0a1f38da7424)

**Comment by MGThePro** [comment]
I don't know, we don't develop yuzu, we just distribute the builds.

**Comment by MegaMimh** [comment]
Okay, thanks for the answer.
