### ISSUE TITLE
`externals/nx_tzdb/CMakeLists.txt` Errors

### ISSUE THREAD

**Issue by ThisNekoGuy** [pineappleEA/pineapple-src#135]
Not sure if you already know about this, given that appimages are still being supplied, but attempting to build throws an nx_txdb Cmake error:

```cmake
CMake Error at externals/nx_tzdb/CMakeLists.txt:52 (add_subdirectory):
  add_subdirectory given source "tzdb_to_nx" which is not an existing
  directory.


CMake Error at externals/nx_tzdb/CMakeLists.txt:80 (CreateHeader):
  CreateHeader Function invoked with incorrect arguments for function named:
  CreateHeader


-- Configuring incomplete, errors occurred!
```

**Comment by MGThePro** [comment]
Did you try building from the source included in the windows release? Oh and did you run `git submodule update --init --recursive` before building too?

**Comment by ThisNekoGuy** [comment]
> Did you try building from the source included in the windows release?

[Yeah](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yuzu-early-access#n28)

> Oh and did you run `git submodule update --init --recursive` before building too?

I didn't, though, when I added `git submodule update --init --remote --recursive externals/nx_tzdb` and added `vulkan-memory-allocator` as a dependency, then it built fine; thanks for helping find the problem, I'll post the info over there
