### ISSUE TITLE
Yuzu EA is not working on my PC

### ISSUE THREAD

**Issue by hinami-chi** [pineappleEA/pineapple-src#136]
I'm experiencing this error, which occurs when I enter the 'settings' option, preventing me from configuring anything in the application. I even tried installing from `https://aur.archlinux.org/packages/yuzu-early-access` and I'm getting the same result.
```
[hinami@hinami-ms7b84 Descargas]$ ./Linux-Yuzu-EA-3708.AppImage
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 614, resource id: 8482184, major code: 40 (TranslateCoords), minor code: 0
Unhandled SIGSEGV at rip 0x00000000005e8d81
Violación de segmento (`core' generado)
```

**Comment by MGThePro** [comment]
Try deleting your configs ans stuff in ~/.local/share/yuzu and ~/.config/yuzu (but maybe make a backup first)

If you're on wayland also try running yuzu with the env variable `QT_QPA_PLATFORM=xcb`

If neither of the two fix the issue you should probably reach out to the yuzu developers, but try reproducing it on mainline first, they don't like it when people report bugs on Early Access and they're not patrons.

**Comment by hinami-chi** [comment]
I am using X11. For some reason, this error occurs from version 3563 onwards. The version 3561 works fine for me without any issues. Thank you for the help! ;)

**Comment by MGThePro** [comment]
Hmm, if it still works on older versions it's probably related to yuzu itself and not your system, and since we only distribute the builds without changing any code there is nothing we can do. You'll need to report this to yuzu developers.
