### ISSUE TITLE
Yuzu will not start since 3727 Update.

### ISSUE THREAD

**Issue by VileZX** [pineappleEA/pineapple-src#137]
Ever since I updated Yuzu to 3727 with the Yuzu Updater executable I have not been able to fully open Yuzu. It starts for a second and then closes itself out. Not even running it as an administrator is fixing the problem. I hope this isn't gonna be like the Ryuold issue.

Here's what the main folder looks like:
![image](https://github.com/pineappleEA/pineapple-src/assets/94597829/e7aaf092-3058-4967-bf78-fda36b65283a)

**Comment by VileZX** [comment]
Updated to 3728. Still a no go.

**Comment by MGThePro** [comment]
Have you tried completely removing the yuzu folder and updater and reinstalling it

**Comment by VileZX** [comment]
*sigh* So 'Ryuold' situation? I'll give it a go and report back in a few minutes.

**Comment by VileZX** [comment]
Nope. Still the same thing. It opens up for a little bit showing a white screen, then it closes.

**Comment by MGThePro** [comment]
Check the yuzu directory in appdata if you get any logs

**Comment by VileZX** [comment]
I think I might know how to fix this from looking at the recent log. I'll post the results in a few.

**Comment by VileZX** [comment]
Hey, could you link me to the most recent yuzu? It seems that the installer is now installing version 1483.

**Comment by litreee** [comment]
Hey Vile did you figure out any fixes? I'm having the same issue.

**Comment by VileZX** [comment]
Not exactly. I got as close as the 'double tap to add directory' screen before it closed on me. I then noticed that the Yuzu the updater was installing was 1483, possibly YEARS behind the current update.

**Comment by VileZX** [comment]
Btw, Sin213's got a trojan on their updater. Probably best to be careful with other updaters in the future.

**Comment by MGThePro** [comment]
> Not exactly. I got as close as the 'double tap to add directory' screen before it closed on me. I then noticed that the Yuzu the updater was installing was 1483, possibly YEARS behind the current update.

I think I see what the problem is. You installed mainline instead of early access. Mainline is currently at 1485, the two updates above your build probably came out after your comment.

> Btw, Sin213's got a trojan on their updater. Probably best to be careful with other updaters in the future.

No it doesn't. Dont just blindly believe antivirus bs reports.

**Comment by VileZX** [comment]
>> I think I see what the problem is. You installed mainline instead of early access. Mainline is currently at 1485, the two updates above your build probably came out after your comment.
> 
> So where do I go from here
>
>> No it doesn't. Dont just blindly believe antivirus bs reports.
>
>Don't think this is a bs report, chief.
![image](https://github.com/pineappleEA/pineapple-src/assets/94597829/0f0aded2-f658-4dec-825a-24719b4a4a49)

**Comment by VileZX** [comment]
The Windows Defender IS there for a reason.

**Comment by MGThePro** [comment]
It's because windows defender is stupid and sometimes quarantines files simply because they are unsigned. From a quick google search I found multiple reports where defender quarantined programs the poster wrote themselves, calling it the same type of trojan as the one here.

Also sin is a trusted member of the community, I trust him more than I trust microsoft

Oh and the updater in question is also [open source](https://github.com/sinscove/Yuzu-Updater)

**Comment by VileZX** [comment]
...is it this guy?
![image](https://github.com/pineappleEA/pineapple-src/assets/94597829/b67f6fea-748d-4820-a52d-c3cad3984376)

**Comment by MGThePro** [comment]
Yes, although he barely uses github

**Comment by VileZX** [comment]
...Ah shit.

**Comment by VileZX** [comment]
Wait, you sure? The account's not showing any projects, but I did download something from them. Maybe someone's posing as them?

**Comment by MGThePro** [comment]
Yes I am 100% sure. As long as you downloaded the same zip that is in the releases of the repo I sent, it's safe. The project is on the sin's cove github account.

**Comment by VileZX** [comment]
Okay, so...where do I go from here:

>I think I see what the problem is. You installed mainline instead of early access. Mainline is currently at 1485, the two updates above your build probably came out after your comment.

Though, I'd like to know when early access became a patreon thing, I would much more like to know how to fix this.

**Comment by MGThePro** [comment]
Early access has always been a patreon thing.

Uninstall the yuzu and updater thing you have now. If you downloaded the updater from yuzu directly, delete the installer and download it from the liftinstall repo on the pineapple account. That one is modified to let you download early access without a token. Make sure you select early access instead of mainline in the initial setup thing.

**Comment by VileZX** [comment]
Alright, going through the install process.

**Comment by VileZX** [comment]
It still closes on it's own.

**Comment by MGThePro** [comment]
What closes on its own, yuzu or the updater?

**Comment by VileZX** [comment]
Yuzu. It goes through the Telemetry and then whether I click yes, no or just x out of that box, 5 seconds later it closes.

**Comment by MGThePro** [comment]
Ok, send the contents of the log

**Comment by VileZX** [comment]
...The logs don't say anything.
[yuzu_log.txt](https://github.com/pineappleEA/pineapple-src/files/11941721/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/pineappleEA/pineapple-src/files/11941722/yuzu_log.txt.old.txt)

**Comment by MGThePro** [comment]
Delete the yuzu folder in appdata/roaming

Maybe backup your save games first though

**Comment by VileZX** [comment]
A bit too late for the latter, also I've done the former 3 times already.

**Comment by MGThePro** [comment]
Not sure then, but at this point it's no longer a pineapple issue but rather a yuzu issue, which I can't really troubleshoot. Best to ask the yuzu team. But don't tell them you got early access for free.
