### ISSUE TITLE
Mouse stopped working on latest EA updates

### ISSUE THREAD

**Issue by Nirelfsen** [pineappleEA/pineapple-src#140]
The latest Yuzu EA updates makes the Mouse stop working happened to me I believe is from the update Yuzu EA 3725 to the latest Yuzu EA 3739. I play with Keyboard and Mouse. I try to update my Yuzu with every new update. Ths doesnt happen with earlier versions like the 3719 and 3720.

**Comment by MGThePro** [comment]
That's down to yuzu developers to fix, report it to them. We only distribute the builds.
