### ISSUE TITLE
Con,T run with Amd  

### ISSUE THREAD

**Issue by lsv12** [pineappleEA/pineapple-src#144]
[  65.202310] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_NV_geometry_shader_passthrough
[  65.202312] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_NV_viewport_array2
[  65.202313] Render.Vulkan <Info> video_core\vulkan_common\vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_NV_viewport_swizzle
[  65.324871] Debug <Critical> video_core\vulkan_common\vulkan_device.cpp:operator ():756: Assertion Failed!
Unimplemented format query=58
[  65.324896] Debug <Critical> video_core\vulkan_common\vulkan_device.cpp:operator ():672: Assertion Failed!
Format=106 with usage=49153 and type=1 has no defined alternatives and host hardware does not support it

 AMD Ryzen 5 5600 6-Core Processor  AND rx 5600xt 

VERSION 3699 CAN RUN

**Comment by MGThePro** [comment]
This is a problem between yuzu and your system. We just distribute the builds. Ask the yuzu developers for help, but reproduce the problem on mainline first.
