### ISSUE TITLE
Please use newer version of Visual Studio to compile Yuzu EA

### ISSUE THREAD

**Issue by FrostyBits77** [pineappleEA/pineapple-src#146]
It seems that EA builds on this github page are using older version of VS and it uses a lot more memory. I got this info from here; https://www.reddit.com/user/ChucksFeedAndSeed/comments/14xksce/comment/js3cwlp/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by MGThePro** [comment]
We don't build yuzu, we just redistribute builds. Report this to yuzu developers.
