### ISSUE TITLE
Please compile with Web UI

### ISSUE THREAD

**Issue by snoandpetals** [pineappleEA/pineapple-src#150]
ARCropolis, a smash bros mod loader, requires this.
Thank you!
-DYUZU_USE_QT_WEB_ENGINE=ON

**Comment by MGThePro** [comment]
We don't compile yuzu from source, we just distribute the builds provided by the yuzu developers, so we don't have that option. Either approach the yuzu developers about this, or compile your own builds with that option enabled.
