### ISSUE TITLE
Cannot turn off controller vibration

### ISSUE THREAD

**Issue by groovemann** [pineappleEA/pineapple-src#162]
running YUZU EA 4072, XBOX Series X controller, playing TotK, even tho the vibration checkbox is unmarked, my controller still vibrates

I downgraded to YUZU EA 4050 and it's working fine, vibration is off when the checkbox is unmarked and on when its marked

**Comment by MGThePro** [comment]
That's an issue with yuzu, we just distribute the builds. Report it to the developers of yuzu.

Ideally reproduce the issue on a mainline build first, they don't like people reporting issues on Early Access when they're not patrons.
