### ISSUE TITLE
Add a flatpak on flathub.

### ISSUE THREAD

**Issue by AnyCreatureMorph** [pineappleEA/pineapple-src#170]
More people will know about this when uploaded on flathub and more people will donate.

**Comment by MGThePro** [comment]
No. This project never had any monetary motivations or plans to deviate in any way from upstream development. Adding this to flathub would not only extend yuzu's lifespan for no reason, it would also create the expectation of modifying the source code, at the very least to guarantee the compatibility with future versions of operating systems, libraries etc.

This project died with the death of yuzu, and it will remain as nothing more than an archive of old builds.
