### ISSUE TITLE
A mod of pineappleEA I'd like you to publish as an alternate build. Works on Windows 7, doesn't send telemetry to Nintendo

### ISSUE THREAD

**Issue by Anonchan04404** [pineappleEA/pineapple-src#171]
I'm not a marketer so more people that need it would see it if you published it, plus it's based on your final release.

https://github.com/Anonchan04404/yuzu-windows-7/releases/

The only files changed from your last published build are yuzu, yuzu-cmd, and yuzu-room. This is verifiable by hashing.

All that's done here is 4 find-and-replaces in [HxD Hex Editor](https://mh-nexus.de/en/hxd/). This is verifiable if for each file above you HxD the changed and unchanged version, CTRL+K, Enter, then hold F6.

**Comment by MGThePro** [comment]
There is no need to disable any telemetry anymore, yuzu's api has already been shut down. On top of that, Windows 7 support ended 4 years ago. If you hate Windows 10/11 that much, just use Linux. 

I'd rather not condone the use of modified builds that I cannot verify the validity of myself.
