### ISSUE TITLE
Yuzu early access linux builds no longer works.

### ISSUE THREAD

**Issue by Etunts** [pineappleEA/pineapple-src#20]
Yuzu early access builds are not working since 1680th build.I am hyped for shader cache rewrite, and my pc can't run yuzu on windows. please fix it. thanks

**Comment by Etunts** [comment]
i builded it myself and it also didnt helped

**Comment by dazemc** [comment]
The issue seems to be on your system since. I have a working linux build off of 1682. Update linux and try again, what's the error output, if any? Logs are in ~/.config/yuzu

**Comment by Etunts** [comment]
log is empty

**Comment by dazemc** [comment]
Try to start it again from command line then pipe the output right after. $
journalctl -en 200 > log.txt

**Comment by Etunts** [comment]
i am new to linux, can you explain it how will i do it?

**Comment by dazemc** [comment]
The fact that your yuzu logfile is empty shows that it's not even starting.
Try to start yuzu and then open up your terminal and type 'journalctl -en
200 > log.txt' without the quotes. This should create a text file with the
last 200 lines of your linux build's log in your home directory. Upload
that file, log.txt, and post it here. BTW what distro are you using?

**Comment by Etunts** [comment]
umm there is no log file there, i am using manjaro xfce

**Comment by Etunts** [comment]
also i am on i5-5200u and intel hd 5500 with 16 gigs of ram.

**Comment by dazemc** [comment]
There should be no reason that you don't have a log on a default system that is working correctly. '$ journalctl > ~/log.txt' or '# journalctl > /home/*User directory*' should output entire log files. Files should be populated in /var/log as well

**Comment by Etunts** [comment]
[log.txt](https://github.com/pineappleEA/pineapple-src/files/6488907/log.txt)

**Comment by Etunts** [comment]
also my sdl2 is greater than 2.0.14 and i also reinstalled it
