### ISSUE TITLE
Suggestion for a Convenient Download link

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [pineappleEA/pineapple-src#21]
# Suggestion for a Convenient Download link
Please read carefully:

## First URL:
[https://github.com/pineappleEA/pineapple-src/releases/latest/download/Windows-Yuzu-EA.7z](https://github.com/pineappleEA/pineapple-src/releases/latest/download/Windows-Yuzu-EA.7z)

The above URL doesn't work for now. Please read the description below first.

## Second URL:
[https://github.com/pineappleEA/pineapple-src/releases/latest/download/Windows-Yuzu-EA-1793.7z](https://github.com/pineappleEA/pineapple-src/releases/latest/download/Windows-Yuzu-EA-1793.7z)

The above URL will be working until version 1793 is latest. It will stop working once a newer version is released. To make it work, Replace the `1793` in it with the latest version number.

# Description
As you can see, the only difference between the two links is the `-VersionNumber` before `.7z` in the second link.

The first link below would always download the latest release if the filename of the release was `Windows-Yuzu-EA.7z`
But it does not work, because the file name contains the version number. To make this work, we have to add a `-` and the version number before `.7z` as in the second link.

# Suggestion
My suggestion is that keep the file name as `Windows-Yuzu-EA.7z` for all the next releases so that the first link can always download the latest release.

**Comment by MGThePro** [comment]
Generally a good suggestion I'd say, but it would break any existing updaters, which would IMO be reason enough to not implement it. On top of that there are just as convenient ways to get the latest version via the github api or our github.io site, which we'll use for older versions anyways, so there's no point in using the https://github.com/pineappleEA/pineapple-src/releases/latest/download url when we could just use https://github.com/pineappleEA/pineapple-src/releases/tag/ for every link. It's easy enough to figure out which of those is the latest version anyways.

**Comment by RokkumanX** [comment]
As one of many thousands end users who gets these glorious holy grail builds for free I can only say that I'm just glad and grateful for that and don't really care about what you call the .7z archives.

As the system is now I would like to say that it's pretty good as it is, I know the number and I can follow the commits and all changes back to the main yuzu source and know which early access merge will be in the downloaded package.
