### ISSUE TITLE
[Question] Source of the source?

### ISSUE THREAD

**Issue by Tachi107** [pineappleEA/pineapple-src#25]
Might be a stupid question, but where do you get the source of the EA version? Is it included with the Patreon subscription?

**Comment by dazemc** [comment]
Yes

**Comment by Tachi107** [comment]
Thanks for the info :)

**Comment by dazemc** [comment]
> Thanks for the info :)

You can also get the source from yuzu and build it yourself. All EA is, is builds they did so you don't have to

**Comment by Tachi107** [comment]
Oh, so you're saying that the EA subscription is basically https://github.com/yuzu-emu/yuzu-nightly but precompiled?

**Comment by dazemc** [comment]
> Oh, so you're saying that the EA subscription is basically https://github.com/yuzu-emu/yuzu-nightly but precompiled?

Yes

**Comment by Tachi107** [comment]
Oh ok, that's interesting. So why is this repo needed? Is it only for the "linux specific patches"?

**Comment by dazemc** [comment]
Oh sorry not that repo, last build was over 2 months ago on there. I was talking about the main branch.... The last commit was 6 hours ago. I think you get access to an EA branch with Patreon but the official main branch is only a few commits behind if you were to compile it right this second

**Comment by Tachi107** [comment]
Got it. Thanks again!
