### ISSUE TITLE
Yuzu Crashes when force saving in pokemon sword

### ISSUE THREAD

**Issue by TacoCatBackWardsIsTacoCat** [pineappleEA/pineapple-src#27]
I am playing pokemon sword in the isle of armor and when using the "Cra-o-matic" (A in game item that requires force saving) My game often gets stuck on the Saving screen and the game crashes and I will lose unsaved data. Is there a fix for this?

**Comment by RokkumanX** [comment]
I think you have a better chance getting help in the official [Yuzu Issue Tracker](https://github.com/yuzu-emu/yuzu/issues)

Also they are pretty picky with uploading your log file so don't forget to include it in your issue.

**Comment by MGThePro** [comment]
Yes emulation related bugs aren't really up to us to fix. You can try [Ryujinx](https://github.com/Ryujinx/Ryujinx) though.
