### ISSUE TITLE
[Ubuntu] Gamepad stick direction inverted

### ISSUE THREAD

**Issue by Pependos2** [pineappleEA/pineapple-src#35]
In few recent releases I found that when I press my _left_ gamepad stick in _left_ direction then Samus runs **to the right**. Conversely, when I press my _left_ gamepad stick in _right_ direction then Samus runs **to the left**. Similarly, the _right_ stick inverted vertically.

When I look into Yuzu gamepad properties, I found the same behaviour.

The last good working release - **Yuzu-EA-2174.AppImage**. The last release I tested was **Yuzu-EA-2189.AppImage**, gamepad not work properly.

**Comment by MGThePro** [comment]
EA 2177 had a huge input rewrite (for whatever reason yuzu even needs to hype up input rewrites), it's probably related to that. Not really our thing to fix, we provide 100% the same source code and executables that come from yuzu, and that wont change.

[Here's](https://github.com/yuzu-emu/yuzu/pull/7255) the link to the PR if you're curious.
