### ISSUE TITLE
Ipega Control - PG 9025 Reversed Analogs

### ISSUE THREAD

**Issue by RannyZyzz** [pineappleEA/pineapple-src#38]
After implementing the controls from the kraken project, this control reversed the left analog on the X axis and the right analog on the Y axis.

https://user-images.githubusercontent.com/44988166/142225686-71dfa4ac-9fd0-4444-b01e-306b33ee8a7c.mp4

**Comment by qurious-pixel** [comment]
Cannot reproduce.

Change your axes to the following:
```
Eixo 3- {up} 
Eixo 3+ {down}

Eixo 0+ {left}
Eixo 0- {right}
```
See if that corrects, and save that as your controller profile.

**Comment by MGThePro** [comment]
Yea, seems like a configuration error. Also not our problem to fix, we just provide builds and source as is. Changes to the source code are meant to be done by the yuzu developers, not us.

**Comment by RannyZyzz** [comment]
@qurious-pixel and @MGThePro 

It worked!

It is now fully functional, thank you very much. :heart:
