### ISSUE TITLE
Suggestion to add aarch64 architecture

### ISSUE THREAD

**Issue by xuancong84** [pineappleEA/pineapple-src#43]
Thank you very much for making appImages for Yuzu!

Nowadays, aarch64 (arm64) is getting more and more popular because it has lower power consumption and higher computational energy efficiency than x86. Many devices such as Raspberry Pi are using aarch64 already, even on Amazon cloud, ARM64 instances are cheaper than x86 instances. Would be nice and useful to add this new architecture.

**Comment by davigamer987** [comment]
I don't think yuzu supports aarch64

**Comment by MGThePro** [comment]
Yea, [dynarmic](https://github.com/merryhime/dynarmic) would have to add aarch64 host support, and yuzu might have to add some more stuff on top as well. That's not something that is in our control either, we just upload the Early Access builds right from yuzu's api.

Ryujinx has put some work into Aarch64 support, but the last status update is from a year ago and there is no public information about completion or release date. It's mentioned [here](https://blog.ryujinx.org/november-december-2020-progress-report/) if you're curious. (Search for raspberry pi to find it)
