### ISSUE TITLE
Auto Updater only works if appimage is located in home dir (linux)

### ISSUE THREAD

**Issue by davigamer987** [pineappleEA/pineapple-src#44]
Auto updater will only work if the app image is in the home dir and it has the default file name, if not it throws a file not found error

**Comment by qurious-pixel** [comment]
The updater does look for the original filename, or it would not know which AppImage to update. And even if it used a wildcard search it would rename it to the original filename.

The file does not need to be in home directory, but requires regular user permissions. `/home` and `/tmp` for example, but not `/usr`.

**Comment by Koppajin** [comment]
Not sure if I should open a new issue but since it's related to auto-updater I figured it'd be ok to reply to this. Getting error re: appimage not being signed
![Screenshot-2021-12-07-11:05:45](https://user-images.githubusercontent.com/5185864/145090805-95f220c9-55fb-440b-9f50-bf1321dd3b06.png)

**Comment by qurious-pixel** [comment]
Not an error, just a notification. Once you close the window, the application will be updated, and will launch.
Official yuzu mainline has the same behavior.

**Comment by Koppajin** [comment]
No, when I close it, it just asks me to update again and this repeats until I choose no to update. Stuck on 2276.
