### ISSUE TITLE
Yuzu stops being able to launch after a couple of reboots. Version EA-2343

### ISSUE THREAD

**Issue by Jiankun-Huang** [pineappleEA/pineapple-src#47]
I get this error whenever I try to launch yuzu. This can be fixed by removing the appimage and launching it again. But Im to lazy to redownload it every time. Im also using Menu Editor to add Yuzu to my menu.
`Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_yuzu-xyBDShz/update.sh: line 3:  7995 Aborted                 (core dumped) zenity --question --timeout=10 --title="yuzu updater" --text="New update available. Update now?" --icon-name=yuzu --window-icon=yuzu.svg --height=80 --width=40`
Currently running Ubuntu 20.04, RTX 2060. Thanks ...

**Comment by qurious-pixel** [comment]
Use version without Auto-Updater to add to the menu. I think this may cause the issue. Or place the AppImage in a location like `~/.local/bin` and point the `.desktop` file to this location.
