### ISSUE TITLE
Yuzu unable to open file explorer or alternative. Version EA-2343

### ISSUE THREAD

**Issue by Jiankun-Huang** [pineappleEA/pineapple-src#48]
Another problum I have with yuzu. Unable to launch file explorer. When opening mod data location, Open save data location, etc. 
`QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
baobab: symbol lookup error: /lib/x86_64-linux-gnu/libgtk-3.so.0: undefined symbol: g_mount_operation_set_is_tcrypt_hidden_volume
Warning: program returned non-zero exit code #32512
Opening "/home/jbx2050/.local/share/yuzu/load/01006A800016E000" with Files  (inode/directory)
nautilus: symbol lookup error: /lib/x86_64-linux-gnu/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
[1225/081029.237438:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Trace/breakpoint trap (core dumped)
XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/lib/x86_64-linux-gnu/libgtk-3.so.0: undefined symbol: g_mount_operation_set_is_tcrypt_hidden_volume
Couldn't load XPCOM.
/usr/bin/xdg-open: 869: iceweasel: not found
/usr/bin/xdg-open: 869: seamonkey: not found
/usr/bin/xdg-open: 869: mozilla: not found
/usr/bin/xdg-open: 869: epiphany: not found
/usr/bin/xdg-open: 869: konqueror: not found
/usr/bin/xdg-open: 869: chromium: not found
/usr/bin/xdg-open: 869: chromium-browser: not found
[1225/081029.710809:ERROR:file_io_posix.cc(152)] open /home/jbx2050/.config/google-chrome/Crash Reports/pending/5929561c-866e-45f0-bdc8-70800c4137cc.lock: File exists (17)
[1225/081029.827208:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Trace/breakpoint trap (core dumped)
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'file:///home/jbx2050/.local/share/yuzu/load/01006A800016E000'
`
Running Ubuntu 20.04, RTX 2060. Thanks ...

**Comment by qurious-pixel** [comment]
This is an issue with how Yuzu processes xdg-open events, specifically on DEs like KDE. 
Because of the mime-type that QT is passing it tries to open the path not only in system file manager, but also browsers, as seen by the error message.

**Comment by Jiankun-Huang** [comment]
Is there anyway to fix this?

**Comment by qurious-pixel** [comment]
Set your file manager as the default application for `inode/directory`.

For example:
`xdg-mime default nautilus.desktop inode/directory` to open with nautilus.
