### ISSUE TITLE
老哥，你的模拟器老崩呀

### ISSUE THREAD

**Issue by lzcchl** [pineappleEA/pineapple-src#49]
我昨天下了你新提交的2358，玩马里奥制造2，上面显示兼容性还是"perfect"呢，结果玩的时候老是崩，能不能提高点稳定性呀

**Comment by qurious-pixel** [comment]
与"柚子"开发人员一起打开问题。我们只是包装。

Open an issue with 'YUZU' developers. PineappleEA
 just packages.
