### ISSUE TITLE
tag the 7z releases as latest?

### ISSUE THREAD

**Issue by beyondmeat** [pineappleEA/pineapple-src#52]
This would make it easier for users and enable scoop as an autoupdater

**Comment by MGThePro** [comment]
I don't know how capable scoop is, but you can easily find the latest windows release via github's API

`curl https://api.github.com/repos/pineappleea/pineapple-src/releases` gives you all releases and download links as a json file. The latest release is always the first link that ends with .7z

**Comment by beyondmeat** [comment]
I'll fix that on scoop.

I know it's not a fork (description for that was changed by the maintainer of that repo), I don't even think you need the bit about linux patches at this point either IIRC they ripped those changes and merged them in

**Comment by beyondmeat** [comment]
I think they prefer what the project description is, so if you update that...
