### ISSUE TITLE
can't start ea-2738 (auto-updater) missing pixbuf

### ISSUE THREAD

**Issue by SteveDevOps** [pineappleEA/pineapple-src#62]
Yo, I'm now unable to start ea-2738 (auto-updater). I'm on pop!_os 22.04.. how to resolve?

`Package gdk-pixbuf-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-pixbuf-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-pixbuf-2.0' found
Package gdk-pixbuf-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-pixbuf-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-pixbuf-2.0' found
yuzu: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2`

**Comment by SteveDevOps** [comment]
Tried to work around with:

`❯ sudo apt install libgdk-pixbuf-2.0-dev                  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libgdk-pixbuf-xlib-2.0-0
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libdeflate-dev libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblzma-dev libpng-dev libpng-tools
  libtiff-dev libtiffxx5
Suggested packages:
  liblzma-doc
The following NEW packages will be installed:
  libdeflate-dev libgdk-pixbuf-2.0-dev libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblzma-dev libpng-dev
  libpng-tools libtiff-dev libtiffxx5
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,092 kB of archives.
After this operation, 4,408 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libdeflate-dev amd64 1.10-2 [59.2 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libjpeg-turbo8-dev amd64 2.1.2-0ubuntu1 [257 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libjpeg8-dev amd64 8c-2ubuntu10 [1,476 B]
Get:4 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libjpeg-dev amd64 8c-2ubuntu10 [1,472 B]
Get:5 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libpng-dev amd64 1.6.37-3build5 [192 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libjbig-dev amd64 2.1-3.1build3 [27.3 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 liblzma-dev amd64 5.2.5-2ubuntu1 [159 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libtiffxx5 amd64 4.3.0-6 [5,732 B]
Get:9 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libtiff-dev amd64 4.3.0-6 [313 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libgdk-pixbuf-2.0-dev amd64 2.42.8+dfsg-1 [47.8 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libpng-tools amd64 1.6.37-3build5 [28.7 kB]
Fetched 1,092 kB in 0s (2,941 kB/s)   
Selecting previously unselected package libdeflate-dev:amd64.
(Reading database ... 286095 files and directories currently installed.)
Preparing to unpack .../00-libdeflate-dev_1.10-2_amd64.deb ...
Unpacking libdeflate-dev:amd64 (1.10-2) ...
Selecting previously unselected package libjpeg-turbo8-dev:amd64.
Preparing to unpack .../01-libjpeg-turbo8-dev_2.1.2-0ubuntu1_amd64.deb ...
Unpacking libjpeg-turbo8-dev:amd64 (2.1.2-0ubuntu1) ...
Selecting previously unselected package libjpeg8-dev:amd64.
Preparing to unpack .../02-libjpeg8-dev_8c-2ubuntu10_amd64.deb ...
Unpacking libjpeg8-dev:amd64 (8c-2ubuntu10) ...
Selecting previously unselected package libjpeg-dev:amd64.
Preparing to unpack .../03-libjpeg-dev_8c-2ubuntu10_amd64.deb ...
Unpacking libjpeg-dev:amd64 (8c-2ubuntu10) ...
Selecting previously unselected package libpng-dev:amd64.
Preparing to unpack .../04-libpng-dev_1.6.37-3build5_amd64.deb ...
Unpacking libpng-dev:amd64 (1.6.37-3build5) ...
Selecting previously unselected package libjbig-dev:amd64.
Preparing to unpack .../05-libjbig-dev_2.1-3.1build3_amd64.deb ...
Unpacking libjbig-dev:amd64 (2.1-3.1build3) ...
Selecting previously unselected package liblzma-dev:amd64.
Preparing to unpack .../06-liblzma-dev_5.2.5-2ubuntu1_amd64.deb ...
Unpacking liblzma-dev:amd64 (5.2.5-2ubuntu1) ...
Selecting previously unselected package libtiffxx5:amd64.
Preparing to unpack .../07-libtiffxx5_4.3.0-6_amd64.deb ...
Unpacking libtiffxx5:amd64 (4.3.0-6) ...
Selecting previously unselected package libtiff-dev:amd64.
Preparing to unpack .../08-libtiff-dev_4.3.0-6_amd64.deb ...
Unpacking libtiff-dev:amd64 (4.3.0-6) ...
Selecting previously unselected package libgdk-pixbuf-2.0-dev:amd64.
Preparing to unpack .../09-libgdk-pixbuf-2.0-dev_2.42.8+dfsg-1_amd64.deb ...
Unpacking libgdk-pixbuf-2.0-dev:amd64 (2.42.8+dfsg-1) ...
Selecting previously unselected package libpng-tools.
Preparing to unpack .../10-libpng-tools_1.6.37-3build5_amd64.deb ...
Unpacking libpng-tools (1.6.37-3build5) ...
Setting up libjpeg-turbo8-dev:amd64 (2.1.2-0ubuntu1) ...
Setting up libpng-tools (1.6.37-3build5) ...
Setting up libpng-dev:amd64 (1.6.37-3build5) ...
Setting up libjbig-dev:amd64 (2.1-3.1build3) ...
Setting up liblzma-dev:amd64 (5.2.5-2ubuntu1) ...
Setting up libjpeg8-dev:amd64 (8c-2ubuntu10) ...
Setting up libdeflate-dev:amd64 (1.10-2) ...
Setting up libtiffxx5:amd64 (4.3.0-6) ...
Setting up libjpeg-dev:amd64 (8c-2ubuntu10) ...
Setting up libtiff-dev:amd64 (4.3.0-6) ...
Setting up libgdk-pixbuf-2.0-dev:amd64 (2.42.8+dfsg-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...

~ on 🅰 (va) took 15s 
❯ ./yuzu-x86_64.AppImage                
yuzu: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2

`

**Comment by SteveDevOps** [comment]
tried latest EA-2743 but same g_memdup2 error.. see other post for workaround and follow that one.. 

https://github.com/pineappleEA/pineapple-src/issues/63

I'll wait on fix.

**Comment by qurious-pixel** [comment]
@SteveDevOps Try this one:

https://github.com/qurious-pixel/pineapple-src/releases/tag/EA-2744

Tested on Pop_OS 22.04 LTS.

Proposed changes in PR #65

**Comment by SteveDevOps** [comment]
Your release works! thx much @qurious-pixel
