### ISSUE TITLE
yuzu: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_memdup2

### ISSUE THREAD

**Issue by XDM-Inc** [pineappleEA/pineapple-src#63]
ever since the latest update im getting this error now when trying to launch yuzu
yuzu: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_memdup2

but if i use the yuzu-x86_64.AppImage.zs-old it works but not the new one

libpango version 1:1.50.7-1 is installed 

i have manjaro kde linux (arch based) installed

the last version to work is Yuzu-EA-2732

**Comment by Csokis** [comment]
Same on Arch (Yuzu-EA-2739). :frowning_face:

**Comment by RANKSHANK** [comment]
It's an incompatibility with libglib-2

You can work around this at the moment by extracting the app image with --appimage-extract and deleting ./squashfs-root/usr/lib/libglib-2.2.0.so.0 and then running ./squashfs-root/AppRun-patched

A bit more tedious than usual but this takes a lot less time deleting and extracting than compiling yuzu for each update so definitely a net time save

**Comment by XDM-Inc** [comment]
> It's an incompatibility with libglib-2
> 
> You can work around this at the moment by extracting the app image with --appimage-extract and deleting ./squashfs-root/usr/lib/libglib-2.2.0.so.0 and then running ./squashfs-root/AppRun-patched
> 
> A bit more tedious than usual but this takes a lot less time deleting and extracting than compiling yuzu for each update so definitely a net time save

i think ill just stay put here unless i need a feature for a game i play. ( i cant even see changelogs anyway, i dont even know whats in these updates)

**Comment by Csokis** [comment]
So this is also caused by libglib-2. I know what to do, I've written it [here](https://github.com/pineappleEA/pineapple-src/issues/29#issuecomment-928939266) before! :wink: The difference is that you only have to delete, not replace. Thanks for the solution RANKSHANK! :sunglasses:

**Comment by Skitals** [comment]
Same on Steam Deck, EA-2743
