### ISSUE TITLE
Pressing stop emulation button when using Vulkan results in app crash

### ISSUE THREAD

**Issue by XDM-Inc** [pineappleEA/pineapple-src#67]
when you try to hit stop emulation via button or by clicking it results in the app crashing instead of going back to the game selector, This crash ONLY happens when using vulkan and not at all with openGL

the command prompt says this

"Unhandled SIGSEGV at rip 0x007fa17c878aa8
/tmp/.mount_yuzu-xFPzite/AppRun: line 18: 43183 Segmentation fault      (core dumped) $APPDIR/AppRun-patched "$@" "

**Comment by MGThePro** [comment]
Does this happen on the official mainline builds too?

Maybe try both their AppImage and the regular binary in the .tar.xz archive in case it's some AppImage related issue.

**Comment by XDM-Inc** [comment]
> Does this happen on the official mainline builds too?
> 
> Maybe try both their AppImage and the regular binary in the .tar.xz archive in case it's some AppImage related issue.

yep i jsut tried all versions of yuzu and they all do it, executable binary, appimage and EA versions

**Comment by MGThePro** [comment]
In that case it's not up to us to fix, and should be reported upstream instead.
