### ISSUE TITLE
We need yuzu-early-access Debian Package (.deb) and Redhat Package (.rpm) for Linux user

### ISSUE THREAD

**Issue by ghost** [pineappleEA/pineapple-src#75]
We need yuzu-early-access Debian/Ubuntu Package (.deb) and Redhat/Fedora Package (.rpm) for Linux user

**Comment by RyzenDew** [comment]
> 

ubuntu does has what's need to build rpm's if need be

**Comment by MGThePro** [comment]
closing this because it is irrelevant now with pinEApple just reuploading linux builds instead of compiling and packaging it from source.
