### ISSUE TITLE
Builds Failing again

### ISSUE THREAD

**Issue by nameless1** [pineappleEA/pineapple-src#77]
> Run mkdir -p "$HOME/.ccache"
> latest: Pulling from quriouspixel/yuzu
> 8e5c1b329fe3: Pulling fs layer
> f362c5b17dee: Pulling fs layer
> 8c304aca8577: Pulling fs layer
> 7559472c7d82: Pulling fs layer
> a3f7f61ecdf2: Pulling fs layer
> 217a6509e563: Pulling fs layer
> 852102ffd33a: Pulling fs layer
> 47cd3072823e: Pulling fs layer
> 47f1bf6dbd98: Pulling fs layer
> 2ed76d58dc86: Pulling fs layer
> 4885acfcf52a: Pulling fs layer
> ed8dce630eaa: Pulling fs layer
> faf8ad13d77d: Pulling fs layer
> aa8cb3da0d41: Pulling fs layer
> 25ede0fe7134: Pulling fs layer
> a3f7f61ecdf2: Waiting
> 217a6509e563: Waiting
> 852102ffd33a: Waiting
> 47cd3072823e: Waiting
> 47f1bf6dbd98: Waiting
> 2ed76d58dc86: Waiting
> 4885acfcf52a: Waiting
> ed8dce630eaa: Waiting
> faf8ad13d77d: Waiting
> aa8cb3da0d41: Waiting
> 25ede0fe7134: Waiting
> 7559472c7d82: Waiting
> f362c5b17dee: Verifying Checksum
> f362c5b17dee: Download complete
> 8e5c1b329fe3: Download complete
> 7559472c7d82: Verifying Checksum
> 7559472c7d82: Download complete
> 217a6509e563: Verifying Checksum
> 217a6509e563: Download complete
> 8e5c1b329fe3: Pull complete
> 852102ffd33a: Verifying Checksum
> 852102ffd33a: Download complete
> a3f7f61ecdf2: Verifying Checksum
> a3f7f61ecdf2: Download complete
> 47cd3072823e: Verifying Checksum
> 47cd3072823e: Download complete
> 47f1bf6dbd98: Verifying Checksum
> 47f1bf6dbd98: Download complete
> 4885acfcf52a: Verifying Checksum
> 4885acfcf52a: Download complete
> 2ed76d58dc86: Verifying Checksum
> 2ed76d58dc86: Download complete
> f362c5b17dee: Pull complete
> ed8dce630eaa: Verifying Checksum
> ed8dce630eaa: Download complete
> faf8ad13d77d: Verifying Checksum
> faf8ad13d77d: Download complete
> aa8cb3da0d41: Verifying Checksum
> aa8cb3da0d41: Download complete
> 25ede0fe7134: Verifying Checksum
> 25ede0fe7134: Download complete
> 8c304aca8577: Verifying Checksum
> 8c304aca8577: Download complete
> 8c304aca8577: Pull complete
> 7559472c7d82: Pull complete
> a3f7f61ecdf2: Pull complete
> 217a6509e563: Pull complete
> 852102ffd33a: Pull complete
> 47cd3072823e: Pull complete
> 47f1bf6dbd98: Pull complete
> 2ed76d58dc86: Pull complete
> 4885acfcf52a: Pull complete
> ed8dce630eaa: Pull complete
> faf8ad13d77d: Pull complete
> aa8cb3da0d41: Pull complete
> 25ede0fe7134: Pull complete
> Digest: sha256:ce5c808b03660112fde7732fc2f1ee78999902d8362eca47001d99257763344e
> Status: Downloaded newer image for quriouspixel/yuzu:latest
> docker.io/quriouspixel/yuzu:latest
> patching file CMakeModules/GenerateSCMRev.cmake
> Hunk #1 FAILED at 11.
> Hunk #2 FAILED at 113.
> 2 out of 2 hunks FAILED -- saving rejects to file CMakeModules/GenerateSCMRev.cmake.rej
> patching file src/common/CMakeLists.txt
> Hunk #1 FAILED at 28.
> 1 out of 1 hunk FAILED -- saving rejects to file src/common/CMakeLists.txt.rej
> total 88
> drwxr-xr-x 21 1001  121 4096 Jul 19 09:05 .
> drwx------  1 root root 4096 Jul 23 20:25 ..
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 0
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 1
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 2
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 3
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 4
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 5
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 6
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 7
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:29 8
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 9
> drwxr-xr-x 17 1001  121 4096 Dec  8  2021 SDL2-2.0.18
> drwxr-xr-x 16 1001  121 4096 May 31 11:03 SDL2-2.0.22
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 a
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 b
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 c
> -rw-r--r--  1 1001  121   16 Jan 22  2021 ccache.conf
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 d
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 e
> drwxr-xr-x 18 1001  121 4096 Jul 20 02:30 f
> drwxr-xr-x  2 1001  121 4096 Jul 20 02:30 tmp
> make: Entering directory '/root/.ccache/SDL2-2.0.22'
> /bin/bash build-scripts/updaterev.sh
> /bin/bash build-scripts/mkinstalldirs /usr/bin
> /usr/bin/install -c -m 755 sdl2-config /usr/bin/sdl2-config
> /bin/bash build-scripts/mkinstalldirs /usr/include/SDL2
> for file in SDL.h SDL_assert.h SDL_atomic.h SDL_audio.h SDL_bits.h SDL_blendmode.h SDL_clipboard.h SDL_cpuinfo.h SDL_egl.h SDL_endian.h SDL_error.h SDL_events.h SDL_filesystem.h SDL_gamecontroller.h SDL_gesture.h SDL_haptic.h SDL_hidapi.h SDL_hints.h SDL_joystick.h SDL_keyboard.h SDL_keycode.h SDL_loadso.h SDL_locale.h SDL_log.h SDL_main.h SDL_messagebox.h SDL_metal.h SDL_misc.h SDL_mouse.h SDL_mutex.h SDL_name.h SDL_opengl.h SDL_opengl_glext.h SDL_opengles.h SDL_opengles2_gl2ext.h SDL_opengles2_gl2.h SDL_opengles2_gl2platform.h SDL_opengles2.h SDL_opengles2_khrplatform.h SDL_pixels.h SDL_platform.h SDL_power.h SDL_quit.h SDL_rect.h SDL_render.h SDL_rwops.h SDL_scancode.h SDL_sensor.h SDL_shape.h SDL_stdinc.h SDL_surface.h SDL_system.h SDL_syswm.h SDL_thread.h SDL_timer.h SDL_touch.h SDL_types.h SDL_version.h SDL_video.h SDL_vulkan.h begin_code.h close_code.h SDL_test.h SDL_test_assert.h SDL_test_common.h SDL_test_compare.h SDL_test_crc32.h SDL_test_font.h SDL_test_fuzzer.h SDL_test_harness.h SDL_test_images.h SDL_test_log.h SDL_test_md5.h SDL_test_memory.h SDL_test_random.h; do \
>     /usr/bin/install -c -m 644 /root/.ccache/SDL2-2.0.22/include/$file /usr/include/SDL2/$file; \
> done
> /usr/bin/install -c -m 644 include/SDL_config.h /usr/include/SDL2/SDL_config.h
> if test -f include/SDL_revision.h; then \
>     /usr/bin/install -c -m 644 include/SDL_revision.h /usr/include/SDL2/SDL_revision.h; \
> else \
>     /usr/bin/install -c -m 644 /root/.ccache/SDL2-2.0.22/include/SDL_revision.h /usr/include/SDL2/SDL_revision.h; \
> fi
> /bin/bash build-scripts/mkinstalldirs /usr/lib
> /bin/bash ./libtool --quiet --mode=install /usr/bin/install -c build/libSDL2.la /usr/lib/libSDL2.la
> /bin/bash ./libtool --quiet --mode=install /usr/bin/install -c build/libSDL2main.la /usr/lib/libSDL2main.la
> /bin/bash ./libtool --quiet --mode=install /usr/bin/install -c build/libSDL2_test.la /usr/lib/libSDL2_test.la
> /bin/bash build-scripts/mkinstalldirs /usr/share/aclocal
> /usr/bin/install -c -m 644 /root/.ccache/SDL2-2.0.22/sdl2.m4 /usr/share/aclocal/sdl2.m4
> /bin/bash build-scripts/mkinstalldirs /usr/lib/pkgconfig
> /usr/bin/install -c -m 644 sdl2.pc /usr/lib/pkgconfig
> /bin/bash build-scripts/mkinstalldirs /usr/lib/cmake/SDL2
> /usr/bin/install -c -m 644 sdl2-config.cmake /usr/lib/cmake/SDL2
> /usr/bin/install -c -m 644 sdl2-config-version.cmake /usr/lib/cmake/SDL2
> make: Leaving directory '/root/.ccache/SDL2-2.0.22'
> 2.0.22
> Requirement already up-to-date: conan in /usr/local/lib/python3.8/dist-packages (1.50.0)
> Requirement already satisfied, skipping upgrade: pluginbase>=0.5 in /usr/local/lib/python3.8/dist-packages (from conan) (1.0.1)
> Requirement already satisfied, skipping upgrade: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.8/dist-packages (from conan) (2.8.2)
> Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.3.3 in /usr/local/lib/python3.8/dist-packages (from conan) (0.4.5)
> Requirement already satisfied, skipping upgrade: Jinja2<4.0.0,>=3.0; python_version >= "3" in /usr/local/lib/python3.8/dist-packages (from conan) (3.1.2)
> Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.26.6 in /usr/local/lib/python3.8/dist-packages (from conan) (1.26.10)
> Requirement already satisfied, skipping upgrade: fasteners>=0.14.1 in /usr/local/lib/python3.8/dist-packages (from conan) (0.17.3)
> Requirement already satisfied, skipping upgrade: patch-ng<1.18,>=1.17.4 in /usr/local/lib/python3.8/dist-packages (from conan) (1.17.4)
> Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.25 in /usr/local/lib/python3.8/dist-packages (from conan) (2.28.1)
> Requirement already satisfied, skipping upgrade: PyJWT<3.0.0,>=2.4.0 in /usr/local/lib/python3.8/dist-packages (from conan) (2.4.0)
> Requirement already satisfied, skipping upgrade: node-semver==0.6.1 in /usr/local/lib/python3.8/dist-packages (from conan) (0.6.1)
> Requirement already satisfied, skipping upgrade: pygments<3.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from conan) (2.12.0)
> Requirement already satisfied, skipping upgrade: six<=1.16.0,>=1.10.0 in /usr/lib/python3/dist-packages (from conan) (1.14.0)
> Requirement already satisfied, skipping upgrade: distro<=1.6.0,>=1.0.2; sys_platform == "linux" or sys_platform == "linux2" in /usr/local/lib/python3.8/dist-packages (from conan) (1.6.0)
> Requirement already satisfied, skipping upgrade: PyYAML<=6.0,>=3.11 in /usr/local/lib/python3.8/dist-packages (from conan) (6.0)
> Requirement already satisfied, skipping upgrade: bottle<0.13,>=0.12.8 in /usr/local/lib/python3.8/dist-packages (from conan) (0.12.21)
> Requirement already satisfied, skipping upgrade: tqdm<5,>=4.28.1 in /usr/local/lib/python3.8/dist-packages (from conan) (4.64.0)
> Requirement already satisfied, skipping upgrade: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2<4.0.0,>=3.0; python_version >= "3"->conan) (2.1.1)
> Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.25->conan) (2019.11.28)
> Requirement already satisfied, skipping upgrade: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.25->conan) (2.8)
> Requirement already satisfied, skipping upgrade: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.25->conan) (2.1.0)
> Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
> -- The C compiler identification is GNU 11.1.0
> -- The CXX compiler identification is GNU 11.1.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/lib/ccache/gcc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/lib/ccache/g++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Downloading compatibility list for yuzu...
> -- [download 1% complete]
> -- [download 5% complete]
> -- [download 7% complete]
> -- [download 9% complete]
> -- [download 10% complete]
> -- [download 14% complete]
> -- [download 17% complete]
> -- [download 29% complete]
> -- [download 36% complete]
> -- [download 76% complete]
> -- [download 100% complete]
> -- Target architecture: x86_64
> CMake Error at CMakeLists.txt:159 (find_package):
>   Could not find a configuration file for package "fmt" that is compatible
>   with requested version "8.0.1".
>   The following configuration files were considered but not accepted:
>     /usr/lib/x86_64-linux-gnu/cmake/fmt/fmt-config.cmake, version: 6.1.2
>     /lib/x86_64-linux-gnu/cmake/fmt/fmt-config.cmake, version: 6.1.2
> -- Configuring incomplete, errors occurred!
> See also "/yuzu/build/CMakeFiles/CMakeOutput.log".
> ninja: error: loading 'build.ninja': No such file or directory
> + BUILDBIN=/yuzu/build/bin
> + BINFILE=yuzu-x86_64.AppImage
> + LOG_FILE=/root/curl.log
> ++ echo main
> + BRANCH=main
> + export CC=gcc-11
> + CC=gcc-11
> + export CXX=g++-11
> + CXX=g++-11
> + cd /tmp
> + curl -sLO https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
> + curl -sLO https://github.com/pineappleEA/pineapple-src/raw/main/.github/workflows/update.tar.gz
> ++ grep 'mkappimage-.*-x86_64.AppImage'
> ++ curl https://github.com/probonopd/go-appimage/releases
> ++ head -n 1
> ++ cut -d '"' -f 2
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  202k    0  202k    0     0   218k      0 --:--:-- --:--:-- --:--:--  218k
> + curl -sL https://github.com/probonopd/go-appimage/releases/download/continuous/mkappimage-715-x86_64.AppImage -o mkappimage.AppImage
> + tar -xzf update.tar.gz
> + chmod a+x linuxdeployqt-continuous-x86_64.AppImage
> + chmod a+x mkappimage.AppImage
> + ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
> squashfs-root/.DirIcon
> squashfs-root/AppRun
> squashfs-root/linuxdeployqt.desktop
> squashfs-root/linuxdeployqt.svg
> squashfs-root/usr
> squashfs-root/usr/bin
> squashfs-root/usr/bin/appimagetool
> squashfs-root/usr/bin/desktop-file-validate
> squashfs-root/usr/bin/linuxdeployqt
> squashfs-root/usr/bin/patchelf
> squashfs-root/usr/bin/qt.conf
> squashfs-root/usr/bin/zsyncmake
> squashfs-root/usr/lib
> squashfs-root/usr/lib/appimagekit
> squashfs-root/usr/lib/appimagekit/mksquashfs
> squashfs-root/usr/lib/libQt5Core.so.5
> squashfs-root/usr/lib/libglib-2.0.so.0
> squashfs-root/usr/lib/libicudata.so.55
> squashfs-root/usr/lib/libicui18n.so.55
> squashfs-root/usr/lib/libicuuc.so.55
> squashfs-root/usr/lib/libpcre.so.3
> squashfs-root/usr/share
> squashfs-root/usr/share/doc
> squashfs-root/usr/share/doc/libglib2.0-0
> squashfs-root/usr/share/doc/libglib2.0-0/copyright
> squashfs-root/usr/share/doc/libicu55
> squashfs-root/usr/share/doc/libicu55/copyright
> squashfs-root/usr/share/doc/libpcre3
> squashfs-root/usr/share/doc/libpcre3/copyright
> squashfs-root/usr/share/doc/qt59base
> squashfs-root/usr/share/doc/qt59base/copyright
> squashfs-root/usr/translations
> + cd /root
> + mkdir -p squashfs-root/usr/bin
> + cp -P /yuzu/build/bin/yuzu /root/squashfs-root/usr/bin/
> cp: cannot stat '/yuzu/build/bin/yuzu': No such file or directory
> Error: Process completed with exit code 1.
>

**Comment by MGThePro** [comment]
fixed.
