### ISSUE TITLE
Auto-updater failing to update itself

### ISSUE THREAD

**Issue by OlegAckbar** [pineappleEA/pineapple-src#78]
Ubuntu 22.04
![image](https://user-images.githubusercontent.com/9915567/180962103-3bafb4dd-b1e9-4160-8cab-23067fbb3b0b.png)

**Comment by MGThePro** [comment]
Yea that's because the build is failing again.

**Comment by OlegAckbar** [comment]
> Yea that's because the build is failing again.
Compilation with gcc-11 is buggy atm, switching to clang should fix issues

**Comment by redsett** [comment]
Any updates on this issue? Ty!

As a Steam Deck user, this would be awesome to have. :)

**Comment by Mario-119** [comment]
> Any updates on this issue? Ty!
> 
> As a Steam Deck user, this would be awesome to have. :)

Same here, this would be extremely helpful

**Comment by MGThePro** [comment]
> > Yea that's because the build is failing again.
> 
> Compilation with gcc-11 is buggy atm, switching to clang should fix issues

It doesn't. Strangely, it doesnt seem like yuzu's CI is even compiling the problematic announce_multiplayer_session.cpp according to the build log, and I have no idea why.

**Comment by MGThePro** [comment]
should work again
