### ISSUE TITLE
your appimage buildbot seems to be malfunctioning for a couple of days now ( cp:  cannot stat '/yuzu/build/bin/yuzu': No such file or directory Error: Process completed with exit code 1.)

### ISSUE THREAD

**Issue by XDM-Inc** [pineappleEA/pineapple-src#80]
on your actions tab here on github your appimage builder has been trying to build new versions for days now but is missing a folder it seems?

 cp: 
cannot stat '/yuzu/build/bin/yuzu': No such file or directory
Error: Process completed with exit code 1.

**Comment by Melechtna** [comment]
The issue seems to stem specifically from here

`/tmp/pineapple/pineappleEA-pineapple-src-569d5e0/src/core/announce_multiplayer_session.cpp:34:43: error: invalid use of incomplete type ‘class Network::RoomNetwork’
   34 |     std::shared_ptr<Network::Room> room = room_network.GetRoom().lock();`

and as far as I can tell, it's because the networking code was basically slapped in, and most of the class types are incomplete. I honestly don't even understand how this builds in Windows unless the compiler is doing some SERIOUS guess work as to the intent of said code, because yeah, there's bits that seem missing. Unfortunately I don't have time to personally see about correcting for this myself in any reasonable time frame, so, hopefully someone else can reach out to whoever scrapped this out of Citra, and convince them to finish writing it.

**Comment by MGThePro** [comment]
> I honestly don't even understand how this builds in Windows

Not just windows. Their CI for linux handles this just fine as well. And I have no idea why.

**Comment by Melechtna** [comment]
I've been up and down the networking sections in code, and this is the snippet it seems to be taking issue with

`AnnounceMultiplayerSession::AnnounceMultiplayerSession(Network::RoomNetwork& room_network_)
    : room_network{room_network_} {
#ifdef ENABLE_WEB_SERVICE
    backend = std::make_unique<WebService::RoomJson>(Settings::values.web_api_url.GetValue(),
                                                     Settings::values.yuzu_username.GetValue(),
                                                     Settings::values.yuzu_token.GetValue());
#else
    backend = std::make_unique<AnnounceMultiplayerRoom::NullBackend>();
#endif
}`

room_network, for whatever reason (and I seriously can't figure out what else it needs to be happy with this class) is not defined to the compilers satisfaction. Even going to far as to set -DENABLE_WEB_SERVICE during compile time is not enough to make it happy.

**Comment by XDM-Inc** [comment]
> I've been up and down the networking sections in code, and this is the snippet it seems to be taking issue with
> 
> `AnnounceMultiplayerSession::AnnounceMultiplayerSession(Network::RoomNetwork& room_network_) : room_network{room_network_} { #ifdef ENABLE_WEB_SERVICE backend = std::make_unique<WebService::RoomJson>(Settings::values.web_api_url.GetValue(), Settings::values.yuzu_username.GetValue(), Settings::values.yuzu_token.GetValue()); #else backend = std::make_unique<AnnounceMultiplayerRoom::NullBackend>(); #endif }`
> 
> room_network, for whatever reason (and I seriously can't figure out what else it needs to be happy with this class) is not defined to the compilers satisfaction. Even going so far as to set -DENABLE_WEB_SERVICE during compile time is not enough to make it happy.
I'm that subject right quick.
I saw those network settings. Is this like a type of online multiplayer implication like ryujinx ldn? Or is it local lab only?

**Comment by XDM-Inc** [comment]
> I've been up and down the networking sections in code, and this is the snippet it seems to be taking issue with
> 
> `AnnounceMultiplayerSession::AnnounceMultiplayerSession(Network::RoomNetwork& room_network_) : room_network{room_network_} { #ifdef ENABLE_WEB_SERVICE backend = std::make_unique<WebService::RoomJson>(Settings::values.web_api_url.GetValue(), Settings::values.yuzu_username.GetValue(), Settings::values.yuzu_token.GetValue()); #else backend = std::make_unique<AnnounceMultiplayerRoom::NullBackend>(); #endif }`
> 
> room_network, for whatever reason (and I seriously can't figure out what else it needs to be happy with this class) is not defined to the compilers satisfaction. Even going so far as to set -DENABLE_WEB_SERVICE during compile time is not enough to make it happy.

On that subject real quick that Network setting, is it something like ryujinx LDN or is it strictly local only?

**Comment by Melechtna** [comment]
> > I've been up and down the networking sections in code, and this is the snippet it seems to be taking issue with
> > `AnnounceMultiplayerSession::AnnounceMultiplayerSession(Network::RoomNetwork& room_network_) : room_network{room_network_} { #ifdef ENABLE_WEB_SERVICE backend = std::make_unique<WebService::RoomJson>(Settings::values.web_api_url.GetValue(), Settings::values.yuzu_username.GetValue(), Settings::values.yuzu_token.GetValue()); #else backend = std::make_unique<AnnounceMultiplayerRoom::NullBackend>(); #endif }`
> > room_network, for whatever reason (and I seriously can't figure out what else it needs to be happy with this class) is not defined to the compilers satisfaction. Even going so far as to set -DENABLE_WEB_SERVICE during compile time is not enough to make it happy.
> 
> On that subject real quick that Network setting, is it something like ryujinx LDN or is it strictly local only?

[https://github.com/citra-emu/citra/blob/master/src/common/](https://github.com/citra-emu/citra/blob/master/src/common/thread.h)

It looks to be ripped straight from Citra (the Yuzu team is the same that worked on citra) especially if you compare the files, very little is different between them.  As for how it does it....you could say it's similar to LDN, but I haven't really eyeballed the network stack for LDN. It's more or less a modified "lan connection" that handles external stuff too, without touching Nintendos servers, so closer to a normal computer in terms of functionality.

LDN has the added functionality of being able to report the games being played to some kind of server that Ryujinx uses to monitor stuff, and has it's own internal hosting method to some extent, so I'd imagine it's a little less "duct-taped" in than this implementation.

**Comment by PhantomX** [comment]
Removing conflicting src/core/network/network.h fixed for me. I don't think it should be there, because src/core/internal_network/network.h is the same.

**Comment by Melechtna** [comment]
> src/core/network/network.h

You're actually fucking kidding me....it's that simple? It's compiled, it works.

**Comment by MGThePro** [comment]
> Removing conflicting src/core/network/network.h fixed for me. I don't think it should be there, because src/core/internal_network/network.h is the same.

perfect, thanks
