### ISSUE TITLE
AppImage fails to run or integrate (auto-update-less version)

### ISSUE THREAD

**Issue by rabidcopy** [pineappleEA/pineapple-src#82]
When trying to run once or integrate the Yuzu EA 2878 AppImage, nothing happens. If executed in a terminal I get this output.

╰─>$ ./Yuzu-EA-2878.AppImage 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 456, resource id: 12682114, major code: 40 (TranslateCoords), minor code: 0
execv error: No such file or directory
 
When running the AppImage obtained from the linux artifact [here](https://github.com/yuzu-emu/yuzu/actions/runs/2768174431) I get this output and Yuzu opens successfully and it can also be integrated successfully.

╰─>$ ./yuzu--20220731-ddf60b788.AppImage 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 463, resource id: 12694021, major code: 40 (TranslateCoords), minor code: 0

When running the auto-updating AppImage obtained from this repository I get this output and Yuzu opens successfully.

╰─>$ ./yuzu-x86_64.AppImage 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 463, resource id: 12696370, major code: 40 (TranslateCoords), minor code: 0

I know this isn't a huge deal considering the auto-updating one works fine and people may gravitate towards that one for its convenience, but it might lead to some confusion for those grabbing AppImages without the auto-updater only to find it doesn't work. Also being thorough, this issue does seem to affect older AppImages such as 2859. So I'm not entirely sure how far this goes back.

**Comment by MGThePro** [comment]
Since we're no longer using a self built appimage, this should be fixed now
