### ISSUE TITLE
Lost saved data while using latest EA build 2885

### ISSUE THREAD

**Issue by macki-sushi** [pineappleEA/pineapple-src#83]
Looks like there's a bug on saving or accessing data on EA build 2885. I'm playing Baldo the Guardian Owls and for the second time now, I'm losing save game data.
![image](https://user-images.githubusercontent.com/67351950/182290190-85505dab-4397-4252-8438-eddd2ac22a17.png)

**Comment by MGThePro** [comment]
Sorry for the late reply, but this has nothing to do with pinEApple. The windows builds are the same as with legit patrons, so this is a yuzu issue, not a pinEApple issue.
