### ISSUE TITLE
Opening save/mod/cache locations of games does not bring up file manager in Linux.

### ISSUE THREAD

**Issue by rabidcopy** [pineappleEA/pineapple-src#84]
Effects 2888 EA auto-updating AppImage. File manager used is Thunar. Works fine on a recent AppImage taken from [https://github.com/yuzu-emu/yuzu/suites/7652237454/artifacts/318623784](https://github.com/yuzu-emu/yuzu/suites/7652237454/artifacts/318623784). If I manually change the default application used to open inode/directory to PCManFM-Qt, opening save/mod/cache locations with the right click menu works. Output in the terminal when attempting to use Thunar as the default file manager is as follows.

exo-open: symbol lookup error: /usr/lib/libgtk-3.so.0: undefined symbol: pango_font_family_get_face

So it appears to be an issue with file managers that use GTK?

Edit: It appears to be related to the included libpango-1.0.so.0 in the AppImage. Repackaging the AppImage with libpango-1.0.so.0 from my own system's /usr/lib fixes the issue. Installed version of pango on my system is 1:1.50.8-1.

**Comment by MGThePro** [comment]
Since we're no longer using a self built appimage, this should be fixed now
