### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by ordovice** [pineappleEA/pineapple-src#85]
When running the EA appimage on Batocera, it reports that libthai.so.0 is missing.

**Comment by ordovice** [comment]
It appears this broke sometime around 2814

**Comment by ordovice** [comment]
Apparently libthai.so is included on the AppImage build excludelist, so OSes that don't include it are out of luck right now unless you start including it.  
https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist

**Comment by MGThePro** [comment]
If it's in the AppImage build excludelist, is it really a pinEApple issue and not an appimage or batocera issue? :thinking:

**Comment by MGThePro** [comment]
Since we're no longer using a self built appimage, this should be fixed now. If it doesnt work with 3088 it's outside of our control
