### ISSUE TITLE
CTR Nitro Fueled going Freeze after playing 5-10 minutes

### ISSUE THREAD

**Issue by bagarang** [pineappleEA/pineapple-src#86]
Hello.. sorry if i make this. i want told you about the last yuzu ea update from you.. 
1. it works great for pokemon Sword and shield and other games i have
2. when i play CTR (1.0.15).. it work good.. and the the loading screen was long about 5-10 minutes till play.. after 5-10 minutes.. the game goin freeze but sound still work there ( i use openGL).. then i change to Vulkan and the glitches come for this game.. well i change back to openGL again and that problem still happend.. 
3. my laptop spesification 
- Core i5-5200
- Nvidia Ge force 930M 2gb 
- 12 gb of ram
- Windows 10 64

**Comment by MGThePro** [comment]
We're not providing support for yuzu, we're just uploading the builds. You should ask the yuzu developers about any issues.

But of course don't tell them you got yuzu from here ^^

**Comment by bagarang** [comment]
Thank you for replying.. thank your for your creation
