### ISSUE TITLE
Pokemon Arceus Bug

### ISSUE THREAD

**Issue by Ohookkk** [pineappleEA/pineapple-src#87]
![yuzu Early Access 2901 _ Pokémon Legends_ Arceus (64-bit) _ 1 1 1 _ NVIDIA 14_08_2022 13_33_36](https://user-images.githubusercontent.com/94994282/184534838-33631edf-5e79-4e7e-9746-18c075be7808.png)
When i try to change the pokemons

**Comment by MGThePro** [comment]
Emulator issue. We don't write the emulator, we just distribute the builds.

Report this to the yuzu developers instead. But of course don't mention that you got the build from here ;)
