### ISSUE TITLE
version 'GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Anonymous941** [pineappleEA/pineapple-src#88]
When I try to start the AppImage, I get this output:

```
Package gdk-pixbuf-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-pixbuf-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-pixbuf-2.0' found
Package gdk-pixbuf-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-pixbuf-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-pixbuf-2.0' found
yuzu: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by yuzu)
yuzu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by yuzu)
```

Followed by the line

`yuzu: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by <something>)`

repeated several times.  I tried to install `GLIBC_2.29` but have no idea what it is or how to get it.

**Comment by Anonymous941** [comment]
Running `sudo apt install libgdk-pixbuf-2.0` removed the lines about `libgdk-pixbuf-2.0`, but `GLIBC` remains.

**Comment by MGThePro** [comment]
Strange, I dont get this error at all and am on Glibc version 2.36. What distro are you using?

**Comment by Anonymous941** [comment]
> Strange, I dont get this error at all and am on Glibc version 2.36. What distro are you using?

Deepin Linux 20.

**Comment by qurious-pixel** [comment]
The version of GLIBC is not supported.  The minimum is 2.31.

**Comment by Anonymous941** [comment]
> The version of GLIBC is not supported. The minimum is now 2.31.
> 
> @Anonymous941 you could try: `early-access version 2859` That version and below had the lower GLIBC version.

I just tried that, same issue.  Do you know how I can upgrade my GLIBC version?

**Comment by qurious-pixel** [comment]
Deepin 23 preview is using version 2.35. 
Deepin 20 uses 2.28, which is older than the version 2859 uses "2.29"

Not sure if the libc can be updated, since it is based in Debian stable, without upgrading your distro version. (23)

**Comment by Anonymous941** [comment]
> Deepin 23 preview is using version 2.35. Deepin 20 uses 2.28, which is older than the version 2859 uses "2.29"
> 
> Not sure if the libc can be updated, since it is based in Debian stable, without upgrading your distro version. (23)

I tried to upgrade the version and ended up making my system unbootable, so I'll just upgrade to the preview version.
