### ISSUE TITLE
[Feature Request] Rename auto updated version to match original appimage

### ISSUE THREAD

**Issue by KrisCris** [pineappleEA/pineapple-src#90]
I hope the name would match the one currently opening. Just rename the old one to `yuzu.appimage_bk` or something and then name the newly downloaded to `yuzu.appimage` (I assume the original name is yuzu.appimage).

**Comment by qurious-pixel** [comment]
This already happens. The file being updated is renamed to `yuzu-x86_64.AppImage.zsync.old` and the new one is named `yuzu-x86_64.AppImage`

**Comment by KrisCris** [comment]
yeah, but if I've already renamed the file to `yuzu.appimage`, I hope the new file will also be renamed to that.

**Comment by reaperofpower** [comment]
> yeah, but if I've already renamed the file to `yuzu.appimage`, I hope the new file will also be renamed to that.

If you are using emudeck you just need to go to "/home/emudeck/backend/tools/launchers" and change the Yuzu launcher to use the new file name and then it will work as expected.

**Comment by MGThePro** [comment]
The auto updated version is no longer in use, so this issue is no longer relevant
