### ISSUE TITLE
Multiplayer tab not woking, cant use yuzu token

### ISSUE THREAD

**Issue by XDM-Inc** [pineappleEA/pineapple-src#93]
I noticed that the multiplayer server browser does not work in Linux. When using the mainline version of yuzu it works but not this EA version. and also cant login with yuzu token

**Comment by Samueru-sama** [comment]
same issue here.

**Comment by MGThePro** [comment]
Try again with 3088

**Comment by XDM-Inc** [comment]
It is now fixed 👍 thanks!
