### ISSUE TITLE
fedora 37 compile is broken!

### ISSUE THREAD

**Issue by EtereosDawn** [pineappleEA/pineapple-src#94]
CMake Error at CMakeLists.txt:195 (find_package):
  Could not find a package configuration file provided by "Catch2" (requested
  version 2.13.7) with any of the following names:

    Catch2Config.cmake
    catch2-config.cmake

  Add the installation prefix of "Catch2" to CMAKE_PREFIX_PATH or set
  "Catch2_DIR" to a directory containing one of the above files.  If "Catch2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/tmp/pineapple/pineappleEA-pineapple-src-6a74631/build/CMakeFiles/CMakeOutput.log".

**Comment by MGThePro** [comment]
Make sure catch2 is installed

**Comment by EtereosDawn** [comment]
fixed but now I can't compile builds anymore and not because of catch2
