### ISSUE TITLE
AppImage won't launch a game past 3073 version on Steam Deck

### ISSUE THREAD

**Issue by Henatsuka** [pineappleEA/pineapple-src#95]
It seems that I can't launch a single version after 3073, I tried every version past that, but they all crashes when launching a game
[yuzu_log.txt](https://github.com/pineappleEA/pineapple-src/files/9943890/yuzu_log.txt)

**Comment by MGThePro** [comment]
Try again with 3088

**Comment by Henatsuka** [comment]
I can confirm it works again !
