### ISSUE TITLE
Build fail again

### ISSUE THREAD

**Issue by EtereosDawn** [pineappleEA/pineapple-src#96]
pineapple-src-EA-3090.ta     [         <=>                       ] 242,33M  1,37MB/s    em 2m 43s  

2022-11-05 20:34:59 (1,49 MB/s) - “pineapple-src-EA-3090.tar.gz” salvo [254104512]

patching file CMakeModules/GenerateSCMRev.cmake
Hunk #1 FAILED at 11.
Hunk #2 FAILED at 113.
2 out of 2 hunks FAILED -- saving rejects to file CMakeModules/GenerateSCMRev.cmake.rej
patching file src/common/CMakeLists.txt
Hunk #1 FAILED at 28.
1 out of 1 hunk FAILED -- saving rejects to file src/common/CMakeLists.txt.rej
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Defaulting to a Release build
-- Downloading compatibility list for yuzu...
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Target architecture: x86_64
-- Found nlohmann_json: /usr/lib64/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.10.5", minimum required is "3.8") 
-- Found ZLIB: /usr/lib64/libz.so (found suitable version "1.2.11", minimum required is "1.2") 
-- Could NOT find zstd (missing: zstd_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for one of the modules 'libzstd'
-- Found zstd: /usr/lib64/libzstd.so (found suitable version "1.5.2", minimum required is "1.5") 
-- Could NOT find lz4 (missing: lz4_DIR)
-- Checking for one of the modules 'liblz4'
-- Found lz4: /usr/lib64/liblz4.so (found suitable version "1.9.3", minimum required is "1.8") 
-- Found Boost: /usr/include (found suitable version "1.76.0", minimum required is "1.73.0") found components: context 
-- Checking for module 'libva'
--   Found libva, version 1.14.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at externals/CMakeLists.txt:12 (file):
  file COPY cannot find
  "/tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/xbyak/xbyak":
  No such file or directory.

CMake Error at externals/CMakeLists.txt:21 (add_subdirectory):
  The source directory

    /tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/dynarmic

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:36 (add_subdirectory):
  The source directory

    /tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/mbedtls

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:37 (target_include_directories):
  Cannot specify include directories for target "mbedtls" which is not built
  by this project.

CMake Error at externals/CMakeLists.txt:77 (add_subdirectory):
  The source directory

    /tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/enet

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:78 (target_include_directories):
  Cannot specify include directories for target "enet" which is not built by
  this project.

CMake Error at externals/CMakeLists.txt:83 (add_subdirectory):
  The source directory

    /tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/cubeb

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:88 (add_subdirectory):
  The source directory

    /tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/discord-rpc

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:89 (target_include_directories):
  Cannot specify include directories for target "discord-rpc" which is not
  built by this project.

CMake Error at externals/CMakeLists.txt:93 (add_subdirectory):
  The source directory

    /tmp/pineapple/pineappleEA-pineapple-src-6130aef/externals/sirit

  does not contain a CMakeLists.txt file.

-- Found OpenSSL: /usr/lib64/libcrypto.so (found suitable version "3.0.5", minimum required is "1.1")  
CMake Error at externals/opus/CMakeLists.txt:14 (include):
  include could not find requested file:

    opus/opus_functions.cmake

-- Configuring incomplete, errors occurred!
See also "/tmp/pineapple/pineappleEA-pineapple-src-6130aef/build/CMakeFiles/CMakeOutput.log".

------------------------------------------------------------------------------
Compilation failed!
You might want to try an older version of yuzu
If that doesn't help, feel free to contact us on discord in the #linux channel

**Comment by MGThePro** [comment]
Yea this isn't really something I can fix. The source archives that newer yuzu early access versions ship with just have some of the externals folders empty. You could try copying those folders from the regular yuzu repo and building it that way, but there's no guarantee that the regular yuzu and early access use the same versions

**Comment by heavysink** [comment]
On ArchLinux just remove the add_subdirectory(externals) in CMakeLists.txt and it builds. But need to install robin-map, fmt, opus etc. and install everything that is provided externally. Use these flags:

    -DYUZU_USE_BUNDLED_OPUS=OFF \
    -DDYNARMIC_NO_BUNDLED_FMT=ON \
    -DDYNARMIC_NO_BUNDLED_ROBIN_MAP=ON \
    -DYUZU_USE_BUNDLED_FFMPEG=OFF \
    -DYUZU_USE_BUNDLED_LIBUSB=OFF \
    -DYUZU_USE_BUNDLED_QT=OFF \
    -DYUZU_USE_EXTERNAL_SDL2=OFF

**Comment by r2rX** [comment]
> On ArchLinux just remove the add_subdirectory(externals) in CMakeLists.txt and it builds. But need to install robin-map, fmt, opus etc. and install everything that is provided externally. Use these flags:
> 
> ```
> -DYUZU_USE_BUNDLED_OPUS=OFF \
> -DDYNARMIC_NO_BUNDLED_FMT=ON \
> -DDYNARMIC_NO_BUNDLED_ROBIN_MAP=ON \
> -DYUZU_USE_BUNDLED_FFMPEG=OFF \
> -DYUZU_USE_BUNDLED_LIBUSB=OFF \
> -DYUZU_USE_BUNDLED_QT=OFF \
> -DYUZU_USE_EXTERNAL_SDL2=OFF
> ```

Thanks for the tip. Seems to not work for  me as near the end of the cmake process, I get the following error:

```
-- Target architecture: x86_64
-- Could NOT find zstd (missing: zstd_DIR)
-- Could NOT find lz4 (missing: lz4_DIR)
-- Configuring done
CMake Error at src/core/CMakeLists.txt:798 (target_link_libraries):
  Target "core" links to:

    Opus::opus

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

I double-checked the Fedora repo and I definitely have opus, zstd and lz4 (and related -devel packages) installed.

**Comment by heavysink** [comment]
> > On ArchLinux just remove the add_subdirectory(externals) in CMakeLists.txt and it builds. But need to install robin-map, fmt, opus etc. and install everything that is provided externally. Use these flags:
> > ```
> > -DYUZU_USE_BUNDLED_OPUS=OFF \
> > -DDYNARMIC_NO_BUNDLED_FMT=ON \
> > -DDYNARMIC_NO_BUNDLED_ROBIN_MAP=ON \
> > -DYUZU_USE_BUNDLED_FFMPEG=OFF \
> > -DYUZU_USE_BUNDLED_LIBUSB=OFF \
> > -DYUZU_USE_BUNDLED_QT=OFF \
> > -DYUZU_USE_EXTERNAL_SDL2=OFF
> > ```
> 
> Thanks for the tip. Seems to not work for me as near the end of the cmake process, I get the following error:
> 
> ```
> -- Target architecture: x86_64
> -- Could NOT find zstd (missing: zstd_DIR)
> -- Could NOT find lz4 (missing: lz4_DIR)
> -- Configuring done
> CMake Error at src/core/CMakeLists.txt:798 (target_link_libraries):
>   Target "core" links to:
> 
>     Opus::opus
> 
>   but the target was not found.  Possible reasons include:
> 
>     * There is a typo in the target name.
>     * A find_package call is missing for an IMPORTED target.
>     * An ALIAS target is missing.
> ```
> 
> I double-checked the Fedora repo and I definitely have opus, zstd and lz4 (and related -devel packages) installed.

Oops I found that I mistakenly used an old version with the externals present when doing the instruction... My bad.

**Comment by r2rX** [comment]
> @MGThePro I found that the .git .gitmodule files are still present in the source provided by yuzu (actually in the source zip in the Windows yuzu zip provided by you...) in which it should contain all the information for the submodules in externals/. They share the same submodule repository as the mainline does (maybe not the same version though **UPDATE I got the answer from discord support they say they are sharing the same submodules with the mainline, so mainline submodules may work also)**, so it can be fetched upstream for now. I tried the following:
> 
>     1. Download the source tarballs from github, untar it.
> 
>     2. Download the windows yuzu zipfile there, unzip it and unzip the source zip inside the windows yuzu zip.
> 
>     3. Copy .git, .gitmodules, .github files and directories in the parent folder untarred in 1)
> 
>     4. Run git module update --init --recursive
> 
> 
> And the submodules are now inside the code.
> 
> You can try to automate the process at your end before pushing it. Or just link the submodule inside the github repo using the information provided by the package.

Thanks for the tip. It seemed to populate the externals folder with the missing libs but on compilation there's an error (Could NOT find zstd (missing: zstd_DIR)). Just to confirm, what is the compilation string you use to compile (including using system zstd)?
