### ISSUE TITLE
Failed to register AppImage in system via libappimage

### ISSUE THREAD

**Issue by Hadrianneue** [pineappleEA/pineapple-src#99]
Error message when trying to integrate appimage, It backtracks to EA-3088, latest to work as intended was EA-3081.

AppImageLauncher version 2.2.0 on Manjaro.

**EDIT**: this issue is also present on yuzu mainline #9268

**Comment by MGThePro** [comment]
> EDIT: this issue is also present on yuzu mainline #9268

Report this issue to yuzu developers then (but ideally mention mainline only, otherwise they'll ask for proof that you are a patron)

We use the official Appimages now, so we can't modify them ourselves easily
